<?php

namespace BlogFarce\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getBlogComments($blogId, $approved = true)
    {
        $queryBuilder = $this->createQueryBuilder('c')
                ->where('c.blog = :blog_id')
                ->addOrderBy('c.created')
                ->setParameter('blog_id', $blogId);
        
        if ($approved) {
            $queryBuilder->andWhere('c.approved = :approved')
                    ->setParameter('approved', true);
        }
        
        return $queryBuilder->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
