blog_farce_api:
    resource: "@BlogFarceApiBundle/Resources/config/routing.yml"
    prefix:   /

metaclass_user:
    resource: "@MetaclassUserBundle/Resources/config/routing.yml"
    prefix:   /

metaclass_band_info:
    resource: "@MetaclassBandInfoBundle/Resources/config/routing.php"
    prefix:   /

BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_rest:
    resource: "@BlogFarceApiBundle/Resources/config/routing.yml"