# src/BlogFarce/BlogBundle/Resources/config/routing.yml
BlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
        _method:  GET
        
BlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BlogBundle_about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Page:about }
    requirements:
        _method:  GET
        
BlogBundle_blog_show:
    pattern: /blog/{id}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
        
BlogBundle_blog_show_comments:
    pattern: /blog/{id}/comments
    defaults: { _controller: BlogBundle:Blog:showComments }
    requirements:
        _method:   GET
        id: \d+
        
BlogBundle_blog_create_comment:
    pattern: /blog/{id}/comments/new
    defaults: { _controller: BlogBundle:Comment:create }
    requirements:
        _method: POST
        blog_id: \d+